[server]
headless = true

[runner]
# Este parÃ¢metro pode ser usado para especificar o arquivo principal.
# PorÃ©m, vale notar que o Procfile costuma ter prioridade no Streamlit Cloud.
main = "0_ğŸ  InÃ­cio.py"
